# site settings
title: Christine Hausen
subtitle: UX Designer & Social Thinker
email: christinehausen@aol.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tinsehau.github.io" # the base hostname & protocol for your site
author:
street_address: Oudenarder Str. 1a
city: Berlin
state: 
zip_code: 13347
country: Germany
phone: (+49) 15256129156

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
flickr_url: https://www.flickr.com/photos/152382823@N04/albums
instagram_url: https://www.instagram.com/tine_von_hohenschoen/
linkedin_url: https://www.linkedin.com/in/christine-hausen-447288106/
pinterest_url: https://www.pinterest.de/tinsehau/
slack_url:


# build settings
markdown: kramdown

sass:
  style: compressed
